---
- name: tap homebrew/cask-versions
  homebrew_tap: tap=homebrew/cask-versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - xmlstarlet
    - watch
    - rsync
    - htop
    - bash
    - bash-completion
    - cloc
    - curl
    - docker
    - ffmpeg
    - findutils
    - gawk
    - git
    - git-extras
    - git-flow
    - glances
    - gnu-sed
    - gnu-tar
    - gnuplot
    - grep
    - htop-osx
    - jpeg
    - lame
    - ncftp
    - nmap
    - openssl
    - openssl@1.1
    - packer
    - pssh
    - python
    - python3
    - readline
    - sbt
    - sqlite
    - sshuttle
    - terraform
    - tree
    - unar
    - webp
    - wget
    - jq
    - nvm
    - mas
    - kubectl
    - kubectx
    - fzf
    - stern
